#!/bin/zsh

#  Created by Markus Schmid on 28.06.22.
#  Copyright © 2022 Markus Schmid. All rights reserved.

#####################
# ITIS v052622
#####################
declare -A ITIS_1401=(
   ["NR"]=1401
   ["ROOTTAXA"]='50 630578 202423 630577 935939 555705 202422' 
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Complete'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql' 
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises all taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Complete_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_BIRDS_1405=(
   ["NR"]=1405
   ["ROOTTAXANAME"]='Aves'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Birds'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql'
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Aves (Birds) cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Aves_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_TRICHOPTERA_1407=(
   ["NR"]=1407
   ["ROOTTAXANAME"]='Trichoptera'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Trichoptera'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql'
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Trichoptera (Caddisflies) cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Trichoptera_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_COLEOPTERA_1408=(
   ["NR"]=1408
   ["ROOTTAXANAME"]='Coleoptera'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost'
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Coleoptera'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql'
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Coleoptera (Beetles) cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Coleoptera_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_DIPTERA_1409=(
   ["NR"]=1409
   ["ROOTTAXANAME"]='Diptera'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Diptera'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql' 
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Diptera (Flies) cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Diptera_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_HEMIPTERA_1410=(
   ["NR"]=1410
   ["ROOTTAXANAME"]='Hemiptera'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Hemiptera'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql' 
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Hemiptera (True Bugs) cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Hemiptera_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_HYMENOPTERA_1411=(
   ["NR"]=1411
   ["ROOTTAXANAME"]='Hymenoptera'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Hymenoptera'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql' 
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Hymenoptera (Sawflies, Wasps, Ants, Bees) cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Hymenoptera_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_SARCOPTIFORMES_1412=(
   ["NR"]=1412
   ["ROOTTAXANAME"]='Sarcoptiformes'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Sarcoptiformes'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql' 
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Sarcoptiformes (Mites Order) cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Sarcoptiformes_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_ARANEAE_1413=(
   ["NR"]=1413
   ["ROOTTAXANAME"]='Araneae'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Araneae'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql' 
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Araneae (Spiders) cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Araneae_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_INSECTA_1414=(
   ["NR"]=1414
   ["ROOTTAXANAME"]='Insecta'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Insecta'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql' 
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Insecta (Insects) cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Insecta_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)
declare -A ITIS_AMPHIBIA_1415=(
   ["NR"]=1415
   ["ROOTTAXANAME"]='Amphibia'
   ["ROOTDB"]='APPDB/ITIS/ITIS_Complete_220526001/ITIS_Complete_220526001.sqlite'
   ["DBHOSTPOSTGRES"]='localhost' 
   ["BACKBONE"]='ITIS'
   ["PUBLISHED"]='2022-05-26'
   ["NAME"]='Amphibia'
   ["DBSOURCEFILE"]='ITIS/v052622/itisPostgreSql052622/ITIS.sql' 
   ["DBTARGETFILE"]='SYSTEM.sqlite'
   ["DBCONFIGFILE"]='CONFIG.sqlite'
   ["TARGETVERSION"]='220526001' 
   ["TNROFFSET"]=60000000
   ["NAMELANGS"]='de,en,fr,sci'
   ["NATIVELANG"]='en'
   ["RANKLANGS"]='de,en,sci'
   ["CITATION"]='This database comprises the Amphibia cluster taxa from ITIS database, published on 26 May 2022. Retrieved [05, 26, 2022], from the Integrated Taxonomic Information System (ITIS) on-line database, www.itis.gov. https://doi.org/10.5066/F7KH0KBK.'
   ["PURCHASEID_RAW"]='com.mascapp.TaxaDB.ITIS_Amphibia_0522'
   ["PURCHASECONTENTVERSION"]='1.0'
   ["PURCHASECONTENTFEATURE"]='D'
   ["STATUS"]=771)